### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by elhertz** [ryleu/armor-nerf#2]
Bumping so you know people care about your mod lol
Thanks

**Comment by ryleu** [comment]
Glad there's interest! Currently busy with personal stuff, but I have made some progress on the mod. I have 1 or 2 weird crashes to fix and then everything should be good to go.

**Comment by ryleu** [comment]
If you grab the artifact, it very well may work. I haven't done any testing on it yet, but who knows, maybe I got it right first try! https://github.com/ryleu/armor-nerf/actions/runs/11102008531

**Comment by ryleu** [comment]
Beta version published! https://modrinth.com/mod/armor-nerf/version/2.2.0

Please test it out and let me know if it works well for you!
